
-- TABLE: companies

CREATE TABLE companies (
    company_no VARCHAR(255),

    created_by VARCHAR(50),
    created_date TIMESTAMPTZ,

    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMPTZ,

    address TEXT,
    description TEXT,

    logo_url VARCHAR(255),

    name VARCHAR(255) NOT NULL,

    size VARCHAR(255),

    website_url VARCHAR(255),

    CONSTRAINT pk_companies
        PRIMARY KEY (company_no)
);


-- TABLE: skills

CREATE TABLE skills (
    skill_id UUID,

    created_by VARCHAR(50),
    created_date TIMESTAMPTZ,

    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMPTZ,

    name VARCHAR(50),

    CONSTRAINT pk_skills
        PRIMARY KEY (skill_id)
);


-- TABLE: jobs

CREATE TABLE jobs (
    job_id UUID,

    created_by VARCHAR(50),
    created_date TIMESTAMPTZ,

    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMPTZ,

    banner_url VARCHAR(500),

    benefits TEXT,

    currency VARCHAR(3) NOT NULL,

    description TEXT NOT NULL,

    education_level VARCHAR(120),

    employment_type VARCHAR(255) NOT NULL,

    experience_level VARCHAR(255) NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,

    is_deleted BOOLEAN NOT NULL,

    location VARCHAR(255) NOT NULL,

    quantity INTEGER NOT NULL,

    required_experience VARCHAR(120),

    requirements TEXT,

    responsibilities TEXT,

    salary_max NUMERIC(38,2) NOT NULL,

    salary_min NUMERIC(38,2) NOT NULL,

    short_description VARCHAR(300) NOT NULL,

    status VARCHAR(50) NOT NULL,

    title VARCHAR(120) NOT NULL,

    total_applications INTEGER NOT NULL,

    views BIGINT NOT NULL,

    company_id VARCHAR(255) NOT NULL,

    CONSTRAINT pk_jobs
        PRIMARY KEY (job_id),

    CONSTRAINT fk_jobs_company
        FOREIGN KEY (company_id)
        REFERENCES companies(company_no),

    CONSTRAINT chk_jobs_employment_type
        CHECK (
            employment_type IN (
                'FULL_TIME',
                'PART_TIME',
                'CONTRACT',
                'INTERN',
                'REMOTE'
            )
        ),

    CONSTRAINT chk_jobs_experience_level
        CHECK (
            experience_level IN (
                'INTERN',
                'FRESHER',
                'JUNIOR',
                'MID',
                'SENIOR',
                'LEAD'
            )
        ),

    CONSTRAINT chk_jobs_quantity
        CHECK (quantity >= 1),

    CONSTRAINT chk_jobs_status
        CHECK (
            status IN (
                'DRAFT',
                'PUBLISHED',
                'CLOSED'
            )
        ),

    CONSTRAINT chk_jobs_total_applications
        CHECK (total_applications >= 0),

    CONSTRAINT chk_jobs_views
        CHECK (views >= 0)
);

-- INDEXES: jobs

CREATE INDEX idx_jobs_active
ON jobs (status, created_date DESC)
WHERE is_deleted = false;

CREATE INDEX idx_jobs_filter
ON jobs (
    is_deleted,
    status,
    location,
    employment_type,
    created_date DESC
);

CREATE INDEX idx_jobs_salary
ON jobs (
    is_deleted,
    salary_min,
    salary_max
);

CREATE INDEX idx_jobs_title_fts
ON jobs
USING GIN (
    to_tsvector('simple', title)
);

-- TABLE: reports

CREATE TABLE reports (
    report_id UUID,

    created_by VARCHAR(50),
    created_date TIMESTAMPTZ,

    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMPTZ,

    report_content TEXT,

    status VARCHAR(50) NOT NULL,

    job_id UUID NOT NULL,

    CONSTRAINT pk_reports
        PRIMARY KEY (report_id),

    CONSTRAINT fk_reports_job
        FOREIGN KEY (job_id)
        REFERENCES jobs(job_id),

    CONSTRAINT chk_reports_status
        CHECK (
            status IN (
                'PENDING',
                'IN_PROGRESS',
                'RESOLVED',
                'DECLINE'
            )
        )
);

-- INDEXES: reports

CREATE INDEX idx_reports_job_id
ON reports(job_id);

-- TABLE: report_images

CREATE TABLE report_images (
    report_id UUID NOT NULL,

    image_url VARCHAR(255),

    CONSTRAINT fk_report_images_report
        FOREIGN KEY (report_id)
        REFERENCES reports(report_id)
);

-- TABLE: job_skill

CREATE TABLE job_skill (
    job_id UUID NOT NULL,

    skill_id UUID NOT NULL,

    CONSTRAINT pk_job_skill
        PRIMARY KEY (job_id, skill_id),

    CONSTRAINT fk_job_skill_job
        FOREIGN KEY (job_id)
        REFERENCES jobs(job_id),

    CONSTRAINT fk_job_skill_skill
        FOREIGN KEY (skill_id)
        REFERENCES skills(skill_id)
);

-- TABLE: outbox_expired_job_event

CREATE TABLE outbox_expired_job_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    aggregate_id VARCHAR(255),

    payload OID,

    retry_count INTEGER NOT NULL,

    status VARCHAR(50),

    type VARCHAR(50),

    created_by VARCHAR(50),
    created_date TIMESTAMPTZ,

    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMPTZ,

    CONSTRAINT pk_outbox_expired_job_event
        PRIMARY KEY (id)
);