[pytest]
testpaths = tests
asyncio_mode = auto
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --cov=app --cov-branch --cov-config=pytest.ini --cov-report=term-missing --cov-report=html:htmlcov --cov-report=xml:target/site/coverage.xml --junitxml=target/surefire-reports/TEST-recommendation-engine.xml

[coverage:run]
source = app
branch = True
omit =
    app/__init__.py
    app/main.py

[coverage:report]
fail_under = 85
