server:
  port: 8084

spring:
  cloud:
    consul:
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      config:
        enabled: false
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}-${server.port}
        deregister: true
        health-check-critical-timeout: 1m

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.cloud.config: DEBUG