package org.workfitai.apigateway.config;

import lombok.extern.slf4j.Slf4j;
import org.springframework.cloud.gateway.route.RouteLocator;
import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Routes Configuration for API Gateway.
 * <p>
 * Only defines WebSocket route with lb:ws:// protocol.
 * REST API routes are auto-generated by Consul Discovery Locator.
 * </p>
 */
@Configuration
@Slf4j
public class WebSocketRoutesConfig {

    @Bean
    public RouteLocator notificationRoutes(RouteLocatorBuilder builder) {
        log.info("🔌 Configuring WebSocket route (REST API handled by Consul auto-routes)");

        return builder.routes()
                // Only override WebSocket path - must use lb:ws:// protocol
                // Consul auto-generates REST API route: /notification/** → lb://notification
                .route("notification-websocket", r -> r
                        .order(-1) // Higher priority than Consul auto-routes (order 0)
                        .path("/notification/ws/**")
                        .filters(f -> f.stripPrefix(1)) // /notification/ws/** → /ws/**
                        .uri("lb:ws://notification")) // ⚠️ lb:ws:// for WebSocket protocol

                .build();
    }
}